version: '3'
services:
  tsauth-postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./src/database/data:/var/lib/postgres
